### ISSUE TITLE
绘制出来的文本很模糊

### ISSUE THREAD

**Issue by appletonystar** [qyz777/DanmakuKit#1]
如题

**Comment by appletonystar** [comment]
阅读`DanmakuAsyncLayer`的源码，在初始化器里面配置了`contentsScale`：
```
    override init() {
        super.init()
        contentsScale = UIScreen.main.scale
    }
```
然后在创建context的时候，使用了`contentScale`，`UIGraphicsBeginImageContextWithOptions(size, opaque, scale)`。但是在初始化器修改的`contentScale`并没有生效，可能是系统后面重置为默认值1了。我把获取context的代码修改为了`UIGraphicsBeginImageContextWithOptions(size, opaque, UIScreen.main.scale)`，就没有字体模糊的问题了。

**Comment by qyz777** [comment]
好的，感谢反馈，我最近修复

**Comment by qyz777** [comment]
> 阅读`DanmakuAsyncLayer`的源码，在初始化器里面配置了`contentsScale`：
> 
> ```
>     override init() {
>         super.init()
>         contentsScale = UIScreen.main.scale
>     }
> ```
> 
> 然后在创建context的时候，使用了`contentScale`，`UIGraphicsBeginImageContextWithOptions(size, opaque, scale)`。但是在初始化器修改的`contentScale`并没有生效，可能是系统后面重置为默认值1了。我把获取context的代码修改为了`UIGraphicsBeginImageContextWithOptions(size, opaque, UIScreen.main.scale)`，就没有字体模糊的问题了。

好的，明白问题了，我最近修复，你可以先在继承DanmakuCell的子类初始化方法中设置layer.contentsScale = UIScreen.main.scale

**Comment by qyz777** [comment]
> > 阅读`DanmakuAsyncLayer`的源码，在初始化器里面配置了`contentsScale`：
> > ```
> >     override init() {
> >         super.init()
> >         contentsScale = UIScreen.main.scale
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 然后在创建context的时候，使用了`contentScale`，`UIGraphicsBeginImageContextWithOptions(size, opaque, scale)`。但是在初始化器修改的`contentScale`并没有生效，可能是系统后面重置为默认值1了。我把获取context的代码修改为了`UIGraphicsBeginImageContextWithOptions(size, opaque, UIScreen.main.scale)`，就没有字体模糊的问题了。
> > 好的，明白问题了，我最近修复。

**Comment by qyz777** [comment]
问题已修复，请使用1.2.2版本
