### ISSUE TITLE
DanmakuViewAdapter 拦截了点击事件，无法点击下面的SwiftUIView，怎么处理呢？

### ISSUE THREAD

**Issue by DSlience** [qyz777/DanmakuKit#11]

**Comment by qyz777** [comment]
关于SwiftUI和UIKit的手势冲突没有很好的办法处理，你可以设置DanmakuViewAdapter.allowsHitTesting(false)，这样下面的view就能响应事件，这样带来的后果是DanmakuView无法响应手势。

**Comment by DSlience** [comment]
是的，目前是这样处理的。还没找到可以兼容弹幕可以响应的解法。

**Comment by qyz777** [comment]
如果有解法欢迎提PR

**Comment by saddit** [comment]
@qyz777 DanmakuViewAdapter 接受一个ViewBuilder，构建出的视图用NSHostView转为NSView添加到弹幕视图下作为子视图，这样是不是能在没有弹幕接受hitTest的时候，构建出的视图能接收到？

**Comment by qyz777** [comment]
> [@qyz777](https://github.com/qyz777) DanmakuViewAdapter 接受一个ViewBuilder，构建出的视图用NSHostView转为NSView添加到弹幕视图下作为子视图，这样是不是能在没有弹幕接受hitTest的时候，构建出的视图能接收到？

之前没有找到很好的方案，可以尝试一下，如果可行的话欢迎提PR
