### ISSUE TITLE
弹幕如何支持gif动态图显示呢？

### ISSUE THREAD

**Issue by appletonystar** [qyz777/DanmakuKit#2]
如题

**Comment by qyz777** [comment]
你好，目前组件不能直接支持gif图显示，但你可以通过为DanmakuCell的layer添加关键帧动画来实现gif图的显示，后续我会开发支持gif图的展示。

**Comment by appletonystar** [comment]
好的，期待你的好消息。

**Comment by qyz777** [comment]
> 好的，期待你的好消息。

你好，1.3.0版本现已支持展示GIF弹幕，需要引入Gif subspec。可以参考或使用DanmakuGifCell和DanmakuGifCellModel来实现GIF的展示
