### ISSUE TITLE
这是一个bug吧？

### ISSUE THREAD

**Issue by nsis1988** [qyz777/DanmakuKit#3]
```
/// Decide whether to use asynchronous rendering.
    public var displayAsync = true {
        didSet {
            guard let layer = layer as? DanmakuAsyncLayer else { return }
            layer.displayAsync = oldValue
        }
    }
```
设置为oldValue？

**Comment by qyz777** [comment]
> ```
> /// Decide whether to use asynchronous rendering.
>     public var displayAsync = true {
>         didSet {
>             guard let layer = layer as? DanmakuAsyncLayer else { return }
>             layer.displayAsync = oldValue
>         }
>     }
> ```
> 
> 
>      
>   
> 
> 设置为oldValue？

你好，感谢提醒，这确实是一个bug，我明天会修复它

**Comment by qyz777** [comment]
你好，1.3.1版本已修复该bug
