### ISSUE TITLE
DanmakuFloatingTrack内存泄漏

### ISSUE THREAD

**Issue by pujiaxin33** [qyz777/DanmakuKit#4]
如下图所示
![image](https://user-images.githubusercontent.com/12654640/148715923-067baabf-b66d-4f99-9260-47092448c5c3.png)

**Comment by qyz777** [comment]
你好，单看这张图很难判断问题，辛苦提供一下更详细的上下文信息，比如进行了什么操作导致了内存泄漏？是否销毁DanmakView之后还有DanmakuFloatingTrack的内存存在？

**Comment by pujiaxin33** [comment]
就是正常的创建DanmakView，展示了若干个弹幕之后，退出页面，使用Xcode memory graph 工具就能看到DanmakuFloatingTrack没有被释放。

DanmakView是被销毁了的。

**Comment by qyz777** [comment]
> 就是正常的创建DanmakView，展示了若干个弹幕之后，退出页面，使用Xcode memory graph 工具就能看到DanmakuFloatingTrack没有被释放。
> 
> DanmakView是被销毁了的。

了解了，我看一下原因。

**Comment by qyz777** [comment]
> 就是正常的创建DanmakView，展示了若干个弹幕之后，退出页面，使用Xcode memory graph 工具就能看到DanmakuFloatingTrack没有被释放。
> 
> DanmakView是被销毁了的。

补充问一下，退出页面前是否调用了DanmakuView的stop方法？

**Comment by pujiaxin33** [comment]
退出页面前没有调用DanmakuView的stop方法

**Comment by pujiaxin33** [comment]
DanmakuView释放时调用了stop方法，就没有了内存泄漏问题了。感谢及时回复。建议将api使用示例，记录到readme里面。

**Comment by qyz777** [comment]
> DanmakuView释放时调用了stop方法，就没有了内存泄漏问题了。感谢及时回复。建议将api使用示例，记录到readme里面。

好的，感谢你的建议，我这边会完善一下README。另外在代码逻辑，我会改成在DanmakuView释放时默认调stop()方法。
