### ISSUE TITLE
可以支持OC吗？ 加上@objc即可，或者我改一下提个MR

### ISSUE THREAD

**Issue by wang-yapu** [qyz777/DanmakuKit#5]

**Comment by wang-yapu** [comment]
看了下，好像并不是简单加上@objc。。 请问打算适配OC吗？

**Comment by qyz777** [comment]
> 看了下，好像并不是简单加上@objc。。 请问打算适配OC吗？

你好，DanmakuKit内的类继承至NSObject，因此不需要添加@objc。OC工程引入swift组件需要创建桥接文件才能编译成功，我这里本地尝试过OC工程引入DanmakuKit，并没有发现编译问题，你可以贴一下报错的截图

**Comment by qyz777** [comment]
提问者没有进一步回复，关闭该问题

**Comment by wang-yapu** [comment]
您好，前段时间有点忙没及时回复。后来没做这个需求了， 感谢你的回复！后续有时间可以继续探讨
