### ISSUE TITLE
可以支持自定义弹幕么？

### ISSUE THREAD

**Issue by ITzhao** [qyz777/DanmakuKit#6]
写的非常棒，如果能支持自定义弹幕就更好了， 我需要能支持（图标+文字+点赞）类型。

**Comment by qyz777** [comment]
> 写的非常棒，如果能支持自定义弹幕就更好了， 我需要能支持（图标+文字+点赞）类型。

你好，DanmakuKit支持自定义弹幕，你可以继承DanmakuCell后重写displaying方法在里面绘制你需要的内容。如果需要实现点赞后改变该条弹幕内容的需求，可以在点赞后调用cell.layer.setNeedsDisplay重新触发渲染流程，此时会重新调用displaying方法，在其中内重新绘制点赞后的内容即可。

**Comment by ITzhao** [comment]
好的，非常感谢！
