### ISSUE TITLE
打开enableCellReusable属性有什么影响吗？

### ISSUE THREAD

**Issue by bitxeno** [qyz777/DanmakuKit#8]
我发现不打开enableCellReusable属性，弹幕播放久了UI会越来越卡，打开这个属性就正常了，但readme中没有这属性的介绍，请问打开有什么影响吗？

**Comment by qyz777** [comment]
> 我发现不打开enableCellReusable属性，弹幕播放久了UI会越来越卡，打开这个属性就正常了，但readme中没有这属性的介绍，请问打开有什么影响吗？

重新看了一下代码，弹幕动画结束时cell并没有从view上移除，看起来是一个bug需要修复。打开该属性会复用弹幕view，也就解决了这个问题，或者你可以先在弹幕结束展示时手动removeFromSuperView

**Comment by bitxeno** [comment]
多谢解答，那我还是先用这属性，暂时用下来是没问题

**Comment by qyz777** [comment]
> 多谢解答，那我还是先用这属性，暂时用下来是没问题

修复代码已经发布了，可以使用1.4.0，在enableCellReusable为false的情况下也不会出现该性能问题
